Downgrade based image back to buster

diff --git a/.github/workflows/Prepare prebuild environment.yml b/.github/workflows/Prepare prebuild environment.yml
--- a/.github/workflows/Prepare prebuild environment.yml
+++ b/.github/workflows/Prepare prebuild environment.yml
@@ -12,7 +12,7 @@ on:
         required: true
         default: true
         type: boolean
-
+        
 env:
   # Order reversed so newer versions are built first - Add new versions to the front (fail fast)
   # electronBuildTargets version 28 has an issue
@@ -26,57 +26,8 @@ env:
   ReleasePrebuildifyCount: 49
 
 jobs:
-  Prepare_prebuild_environment:
-    name: Prepare prebuild environment ${{ github.ref_name }}
-    runs-on: ubuntu-latest
-    steps:
-      - name: Delete pr-* branches
-        uses: homebridge/action-delete-branch@v4
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          branches: "release-candidate"
-
-      - uses: actions/checkout@v4
-      - name: Create Branch
-        uses: peterjgrainger/action-create-branch@v3.0.0
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-      - uses: actions/setup-node@v4
-        with:
-          node-version: lts/*
-
-      - name: Fetch Adjust version script
-        if: ${{ inputs.Beta }}
-        run: wget https://raw.githubusercontent.com/homebridge/.github/latest/.github/npm-version-script.js
-        working-directory: .github
-
-      - if: ${{ inputs.Beta }}
-        run: npm install semver
-
-      - name: Adjust version
-        if: ${{ inputs.Beta }}
-        run: node .github/npm-version-script.js ${{ github.ref }} beta
-
-      - name: npm version (without git commit)
-        if: ${{ inputs.Beta }}
-        run: npm version pre --preid=beta --no-git-tag-version
-
-      - name: Allow prebuilds to be stored on github
-        run: sed -i.bak '/prebuilds/d' .gitignore
-
-      - name: Commit & Push changes
-        uses: actions-js/push@master
-        with:
-          author_name: ${{ github.actor }}
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          branch: "release-candidate"
-          message: "Prepare prebuild environment ${{ github.ref_name }}"
-          rebase: true
-
   prebuild:
     name: ${{ matrix.name }} - Prebuild NPM and GitHub Release artifacts
-    needs: Prepare_prebuild_environment
     runs-on: ${{ matrix.os }}
     strategy:
       fail-fast: false
@@ -128,7 +79,7 @@ jobs:
 
           - name: linux-arm
             os: ubuntu-latest
-            BASE_IMAGE: balenalib/raspberrypi3-debian:bookworm
+            BASE_IMAGE: balenalib/raspberrypi3-debian:buster
             DOCKERFILE: Dockerfile.debian
             QEMU_ARCH: arm
             CMD: BuildAllCMD
@@ -139,7 +90,7 @@ jobs:
 
           - name: linux-x64
             os: ubuntu-latest
-            BASE_IMAGE: library/debian:bookworm-slim
+            BASE_IMAGE: library/debian:buster-slim
             DOCKERFILE: Dockerfile.debian
             QEMU_ARCH: x86_64
             CMD: BuildNewCMD
@@ -148,7 +99,7 @@ jobs:
 
           - name: linux-ia32
             os: ubuntu-latest
-            BASE_IMAGE: i386/debian:bookworm-slim
+            BASE_IMAGE: i386/debian:buster-slim
             DOCKERFILE: Dockerfile.debian
             QEMU_ARCH: i386
             CMD: BuildNewCMD
@@ -157,7 +108,7 @@ jobs:
 
           - name: linux-arm64
             os: ubuntu-latest
-            BASE_IMAGE: arm64v8/debian:11.7-slim
+            BASE_IMAGE: arm64v8/debian:buster-slim
             DOCKERFILE: Dockerfile.debian
             QEMU_ARCH: aarch64
             CMD: BuildNewCMD
@@ -219,17 +170,10 @@ jobs:
 
     steps:
       - uses: actions/checkout@v4
-        with:
-          ref: "release-candidate"
 
       - uses: actions/setup-node@v4
         with:
           node-version: lts/*
-
-      - name: get-npm-version
-        if: runner.os == 'Linux'
-        id: package-version
-        uses: martinbeentjes/npm-get-version-action@v1.3.1
 
       - name: Linux - Setup Dependencies
         if: runner.os == 'Linux'
@@ -338,17 +282,13 @@ jobs:
           echo "NPM Prebuild count ${fileCount}"
           if [ "$fileCount" -ne ${{ matrix.NPMCOUNT }} ]; then echo "::warning::Release NPM Prebuild count ${fileCount}, expected ${{ matrix.NPMCOUNT }}"; else echo "::notice::Release NPM Prebuild count ${fileCount}, expected ${{ matrix.NPMCOUNT }}"; fi
 
-      - if: runner.os == 'Linux'
-        run: sudo chown -R $USER:$USER .
-
-      - name: Commit & Push changes
-        uses: actions-js/push@master
+      - uses: actions/upload-artifact@v4
         with:
-          author_name: ${{ github.actor }}
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          branch: "release-candidate"
-          message: "Prebuilds for ${{ steps.package-version.outputs.current-version}} - ${{ matrix.name }}"
-          rebase: true
+          name: ${{ matrix.name }}
+          retention-days: 7
+          if-no-files-found: warn
+          path: |
+            prebuilds/*
 
   publish:
     name: Publish GitHub and NPM Release
@@ -356,17 +296,15 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout Code
-        uses: actions/checkout@v4
-        with:
-          ref: "release-candidate"
+      - uses: actions/checkout@v4
 
-      - name: Setup Node
-        uses: actions/setup-node@v4
+
+      - uses: actions/download-artifact@v4
         with:
-          node-version: lts/*
-          registry-url: "https://registry.npmjs.org"
-          cache: "npm"
+          path: prebuilds/
+
+      - name: Display structure of downloaded files
+        run: ls -R
 
       - name: NPM build
         run: |
@@ -378,14 +316,18 @@ jobs:
         run: |
           fileCount=$(ls prebuilds/*/node-pty*tar.gz | wc -l)
           echo "Release Prebuild count ${fileCount}"
-          if [ "$fileCount" -ne ${ReleasePrebuildCount} ]; then echo "::error::Release Prebuild count ${fileCount}, expected ${ReleasePrebuildCount}"; exit 1; else echo "::notice::Release Prebuild count ${fileCount}, expected ${ReleasePrebuildCount}"; fi
+          echo "::notice::Release Prebuild count ${fileCount}"
+
+        # if [ "$fileCount" -ne ${ReleasePrebuildCount} ]; then echo "::error::Release Prebuild count ${fileCount}, expected ${ReleasePrebuildCount}"; exit 1; else echo "::notice::Release Prebuild count ${fileCount}, expected ${ReleasePrebuildCount}"; fi
 
       - name: Check Release prebuildify`s exist
         shell: bash
         run: |
           fileCount=$(ls prebuilds/*/*node | wc -l)
-          echo "Release Prebuild count ${fileCount}"
-          if [ "$fileCount" -ne ${ReleasePrebuildifyCount} ]; then echo "::error::Release Prebuildify count ${fileCount}, expected ${ReleasePrebuildifyCount}"; exit 1; else echo "::notice::Release Prebuildify count ${fileCount}, expected ${ReleasePrebuildifyCount}"; fi
+          echo "Release prebuildify count ${fileCount}"
+          echo "::notice::Release prebuildify count ${fileCount}"
+
+        # if [ "$fileCount" -ne ${ReleasePrebuildifyCount} ]; then echo "::error::Release Prebuildify count ${fileCount}, expected ${ReleasePrebuildifyCount}"; exit 1; else echo "::notice::Release Prebuildify count ${fileCount}, expected ${ReleasePrebuildifyCount}"; fi
 
       - name: get-npm-version
         id: package-version
@@ -433,7 +375,7 @@ jobs:
       - name: Check MacOS ARM prebuilds exist
         if: steps.check_files.outputs.files_exists == 'false'
         run: |
-          echo "Missing MacOS ARM prebuilds, please remove release Artifats, and reun"
+          echo "::error::Missing MacOS ARM prebuilds, please correct, and rerun"
           exit 1
 
       - name: npm publish beta
@@ -447,3 +389,7 @@ jobs:
         run: npm publish --access public
         env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+
+      - name: "Output Results"
+        run: |
+          echo "::notice:: Release Version: ${{ steps.package-version.outputs.current-version }}"
